# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62cc3fe1c89c75ed995f8b398e56cf9009311b2cf301ee5aab4b2d9703fe09f9d40d46d25620a48da3bcf2d7e8f2273d06b1425bacba623ecdefb00246b02dae

test:
  secret_key_base: 7efc756ca392428262fd9c71497737630a5e585b39794f42aceff94ec27795699cccec2e9d5b872ecddfb7fa2cf0d57cbf64ac750667b293add99d7382a06baf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
